## Build me a map, ChatGPT

Build me a run club map from this website:
https://docs.google.com/spreadsheets/d/1QFRce-siqNQsuTEtmCf4zg5uE0W4fTPdJjEDbDVNRLQ/edit?gid=1234181538#gid=1234181538

In [1]:
import pandas as pd
url = 'https://docs.google.com/spreadsheets/d/1QFRce-siqNQsuTEtmCf4zg5uE0W4fTPdJjEDbDVNRLQ/edit?usp=sharing'
sheet_id = url.split('/d/')[1].split('/edit')[0]
export_url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv&gid=274776461'
df = pd.read_csv(export_url)
df.head()

,Borough,Crew,Status,Website,Day,Time,Location,Type of Run,Distance/Run Type,Pace,Meet Up Information,Recognized Organization
0,The Bronx,718Run,Active,https://718run.com/,Thursday,6:30 PM,"Kingbridge Social Club, 3625 Kingsbridge Ave, ...",NaN,NaN,NaN,Free,NaN
1,The Bronx,Boogie Down Bronx Runners,Active,https://www.instagram.com/boogiedownbronxrunners/,Tuesday,7:00 PM,Pelham Cornerstone Community Center - 785 Pelh...,NaN,NaN,NaN,"Free, all levels",NaN
2,The Bronx,Bronx Burners,Active,https://www.instagram.com/bronxburnersrc/,Tuesday,7:00 PM,"The Armory, 216 Fort Washington Ave, New York,...",Track,NaN,NaN,"Free, all levels, winter meetups at the Armory...",NYRR
3,The Bronx,Bronx Femme Run,Active,https://www.instagram.com/bronxfemmerun/,Friday,6:30 PM,"Joseph Yancey Track, East 161st St. &, Macombs...",NaN,"Walk 2.5M, Run/Walk 3.2M, Run 3.5M",NaN,"Every 1st Friday, Free, Womxn club",NaN
4,The Bronx,Bronx Nomads,Active,https://www.instagram.com/bronxnomads/,Monday,6:30 PM,"Williamsbridge Oval Park, 2335 Resevoir Oval E...",NaN,Community Run,NaN,"Free, all levels",NaN

In [187]:
#bronx = df[df['Borough'] == 'Manhattan']
#bronx.shape

In [2]:
print(df.shape)
#df = bronx

#Preprocessing
df_preprocessed = df[df['Status'] == 'Active'] #limiting to active
df_preprocessed = df_preprocessed[df_preprocessed['Location'].notna()] #Limiting to w/ location since it is a map
df_preprocessed = df_preprocessed[~df_preprocessed.Location.str.contains("Varies|social|instagram", case=False, na=False)]
df_preprocessed['Borough'] = df['Borough'].str.replace('The Bronx', 'Bronx') #Cleaning up borough for consistency
df_preprocessed['Weekend'] = df_preprocessed['Day'].isin(['Saturday', 'Sunday']) #Adding weekend indicator
df_preprocessed = df_preprocessed.drop_duplicates() #Drop obvious duplicates

print(df_preprocessed.shape)
df_preprocessed = df_preprocessed.reset_index(drop=True)
df_preprocessed.head()

(425, 12)
(301, 13)

,Borough,Crew,Status,Website,Day,Time,Location,Type of Run,Distance/Run Type,Pace,Meet Up Information,Recognized Organization,Weekend
0,Bronx,Boogie Down Bronx Runners,Active,https://www.instagram.com/boogiedownbronxrunners/,Tuesday,7:00 PM,Pelham Cornerstone Community Center - 785 Pelh...,NaN,NaN,NaN,"Free, all levels",NaN,False
1,Bronx,Bronx Burners,Active,https://www.instagram.com/bronxburnersrc/,Tuesday,7:00 PM,"The Armory, 216 Fort Washington Ave, New York,...",Track,NaN,NaN,"Free, all levels, winter meetups at the Armory...",NYRR,False
2,Bronx,Bronx Femme Run,Active,https://www.instagram.com/bronxfemmerun/,Friday,6:30 PM,"Joseph Yancey Track, East 161st St. &, Macombs...",NaN,"Walk 2.5M, Run/Walk 3.2M, Run 3.5M",NaN,"Every 1st Friday, Free, Womxn club",NaN,False
3,Bronx,Bronx Nomads,Active,https://www.instagram.com/bronxnomads/,Monday,6:30 PM,"Williamsbridge Oval Park, 2335 Resevoir Oval E...",NaN,Community Run,NaN,"Free, all levels",NaN,False
4,Bronx,Bronx Nomads,Active,https://www.instagram.com/bronxnomads/,Thursday,6:30 PM,"Williamsbridge Oval Track, 2335 Resevoir Oval ...",NaN,Track,NaN,"Free, all levels",NaN,False

In [3]:
unique_clubs = df_preprocessed[['Crew', 'Borough', 'Website', 'Location']].drop_duplicates()
unique_clubs

,Crew,Borough,Website,Location
0,Boogie Down Bronx Runners,Bronx,https://www.instagram.com/boogiedownbronxrunners/,Pelham Cornerstone Community Center - 785 Pelh...
1,Bronx Burners,Bronx,https://www.instagram.com/bronxburnersrc/,"The Armory, 216 Fort Washington Ave, New York,..."
2,Bronx Femme Run,Bronx,https://www.instagram.com/bronxfemmerun/,"Joseph Yancey Track, East 161st St. &, Macombs..."
3,Bronx Nomads,Bronx,https://www.instagram.com/bronxnomads/,"Williamsbridge Oval Park, 2335 Resevoir Oval E..."
4,Bronx Nomads,Bronx,https://www.instagram.com/bronxnomads/,"Williamsbridge Oval Track, 2335 Resevoir Oval ..."
...,...,...,...,...
293,Staten Island Athletic Club,Staten Island,https://www.instagram.com/staten_island_athlet...,Clove Lakes Park
294,Staten Island Athletic Club,Staten Island,https://www.instagram.com/staten_island_athlet...,Silver Lake Park
296,Staten Island Athletic Club,Staten Island,https://www.instagram.com/staten_island_athlet...,Greenbelt Nature Center
298,The Just Us Running Club,Staten Island,https://www.instagram.com/thejurcnyc/,Jus' Us Store
300,Yonkers Running Project aka YRP,Yonkers,https://www.instagram.com/yonkersrunningprojec...,100 main st Yonkers NY 10591

## GEOCODE

*Prompt*  

Prompt 1 Chain-of-Thought

I want to geo code addresses using the google maps api. The addresses are stored in the column 'location'. I want to send the api the addresses and then get the lat and long as new columns in my df. I also want to return the status of the api call and the formatted address from the api. 

Prompt 2 Chain-of-Thought
Add borough-specific biasing for better results if first attempt of standard geocoding fails. (Claude automatically came up with third attempt: fuzzy matching.)

Get my API keys

In [4]:
def geocode_address(address, borough=None):
    """Geocode an address using Google Maps API with fallback for approximate matches."""
    try:
        # First attempt: standard geocoding
        response = gmaps.geocode(address)
        
        if response:
            location = response[0]['geometry']['location']
            formatted_address = response[0]['formatted_address']
            result_type = response[0]['types'][0] if 'types' in response[0] else 'unknown'
            return location['lat'], location['lng'], "OK", formatted_address, result_type
            
        # Second attempt: add borough-specific biasing for better results
        if borough:
            # Create a more specific search string with the borough
            borough_search = f"{address}, {borough}, New York City"
            response = gmaps.geocode(borough_search)
            
            if response:
                location = response[0]['geometry']['location']
                formatted_address = response[0]['formatted_address']
                result_type = response[0]['types'][0] if 'types' in response[0] else 'unknown'
                return location['lat'], location['lng'], "BOROUGH_MATCH", formatted_address, result_type
            
        # THIRD attempt: fuzzy matching with geocode places API
        places_response = gmaps.places(address + " New York City")
        
        if places_response['results']:
            place = places_response['results'][0]
            location = place['geometry']['location']
            formatted_address = place['formatted_address'] if 'formatted_address' in place else place['name']
            return location['lat'], location['lng'], "FUZZY_MATCH", formatted_address, "place"
            
        return None, None, "ZERO_RESULTS", None, None
        
    except Exception as e:
        return None, None, "ERROR", str(e), None

In [5]:
#Applying geocode function to preprocessed df
unique_clubs[['latitude', 'longitude', 'api_status', 'formatted_address', 'result_type']] = unique_clubs.apply(
    lambda row: pd.Series(geocode_address(row['Location'], row['Borough'])), 
    axis=1
)

In [6]:
unique_clubs

,Crew,Borough,Website,Location,latitude,longitude,api_status,formatted_address,result_type
0,Boogie Down Bronx Runners,Bronx,https://www.instagram.com/boogiedownbronxrunners/,Pelham Cornerstone Community Center - 785 Pelh...,None,None,ERROR,name 'gmaps' is not defined,None
1,Bronx Burners,Bronx,https://www.instagram.com/bronxburnersrc/,"The Armory, 216 Fort Washington Ave, New York,...",None,None,ERROR,name 'gmaps' is not defined,None
2,Bronx Femme Run,Bronx,https://www.instagram.com/bronxfemmerun/,"Joseph Yancey Track, East 161st St. &, Macombs...",None,None,ERROR,name 'gmaps' is not defined,None
3,Bronx Nomads,Bronx,https://www.instagram.com/bronxnomads/,"Williamsbridge Oval Park, 2335 Resevoir Oval E...",None,None,ERROR,name 'gmaps' is not defined,None
4,Bronx Nomads,Bronx,https://www.instagram.com/bronxnomads/,"Williamsbridge Oval Track, 2335 Resevoir Oval ...",None,None,ERROR,name 'gmaps' is not defined,None
...,...,...,...,...,...,...,...,...,...
293,Staten Island Athletic Club,Staten Island,https://www.instagram.com/staten_island_athlet...,Clove Lakes Park,None,None,ERROR,name 'gmaps' is not defined,None
294,Staten Island Athletic Club,Staten Island,https://www.instagram.com/staten_island_athlet...,Silver Lake Park,None,None,ERROR,name 'gmaps' is not defined,None
296,Staten Island Athletic Club,Staten Island,https://www.instagram.com/staten_island_athlet...,Greenbelt Nature Center,None,None,ERROR,name 'gmaps' is not defined,None
298,The Just Us Running Club,Staten Island,https://www.instagram.com/thejurcnyc/,Jus' Us Store,None,None,ERROR,name 'gmaps' is not defined,None
300,Yonkers Running Project aka YRP,Yonkers,https://www.instagram.com/yonkersrunningprojec...,100 main st Yonkers NY 10591,None,None,ERROR,name 'gmaps' is not defined,None

## Manually verifying addresses that did not have 'OK' api_status

In [7]:
unique_clubs_error = unique_clubs[unique_clubs['api_status'] != 'OK']
unique_clubs_error

,Crew,Borough,Website,Location,latitude,longitude,api_status,formatted_address,result_type
0,Boogie Down Bronx Runners,Bronx,https://www.instagram.com/boogiedownbronxrunners/,Pelham Cornerstone Community Center - 785 Pelh...,None,None,ERROR,name 'gmaps' is not defined,None
1,Bronx Burners,Bronx,https://www.instagram.com/bronxburnersrc/,"The Armory, 216 Fort Washington Ave, New York,...",None,None,ERROR,name 'gmaps' is not defined,None
2,Bronx Femme Run,Bronx,https://www.instagram.com/bronxfemmerun/,"Joseph Yancey Track, East 161st St. &, Macombs...",None,None,ERROR,name 'gmaps' is not defined,None
3,Bronx Nomads,Bronx,https://www.instagram.com/bronxnomads/,"Williamsbridge Oval Park, 2335 Resevoir Oval E...",None,None,ERROR,name 'gmaps' is not defined,None
4,Bronx Nomads,Bronx,https://www.instagram.com/bronxnomads/,"Williamsbridge Oval Track, 2335 Resevoir Oval ...",None,None,ERROR,name 'gmaps' is not defined,None
...,...,...,...,...,...,...,...,...,...
293,Staten Island Athletic Club,Staten Island,https://www.instagram.com/staten_island_athlet...,Clove Lakes Park,None,None,ERROR,name 'gmaps' is not defined,None
294,Staten Island Athletic Club,Staten Island,https://www.instagram.com/staten_island_athlet...,Silver Lake Park,None,None,ERROR,name 'gmaps' is not defined,None
296,Staten Island Athletic Club,Staten Island,https://www.instagram.com/staten_island_athlet...,Greenbelt Nature Center,None,None,ERROR,name 'gmaps' is not defined,None
298,The Just Us Running Club,Staten Island,https://www.instagram.com/thejurcnyc/,Jus' Us Store,None,None,ERROR,name 'gmaps' is not defined,None
300,Yonkers Running Project aka YRP,Yonkers,https://www.instagram.com/yonkersrunningprojec...,100 main st Yonkers NY 10591,None,None,ERROR,name 'gmaps' is not defined,None

In [ ]:
#Checking wrong locations
#print(unique_clubs_error.loc[147])
#print("\nLocation:" , unique_clubs_error.loc[147]['Location'])

In [8]:
#Manually corrected addresses for four run clubs where meetup descriptions required special attention
unique_clubs_error.loc[77, 'Location'] = 'Grand Army Plaza Entrance, Brooklyn'
unique_clubs_error.loc[147, 'Location'] = '910 5th Ave, New York'
unique_clubs_error.loc[185, 'Location'] = '2 W 77th St, New York'
unique_clubs_error.loc[229, 'Location'] = '42 W 14th St, New York'
#Applying geocode function to preprocessed df
unique_clubs_error[['latitude', 'longitude', 'api_status', 'formatted_address', 'result_type']] = unique_clubs_error.apply(
    lambda row: pd.Series(geocode_address(row['Location'], row['Borough'])), 
    axis=1
)
unique_clubs_error

,Crew,Borough,Website,Location,latitude,longitude,api_status,formatted_address,result_type
0,Boogie Down Bronx Runners,Bronx,https://www.instagram.com/boogiedownbronxrunners/,Pelham Cornerstone Community Center - 785 Pelh...,None,None,ERROR,name 'gmaps' is not defined,None
1,Bronx Burners,Bronx,https://www.instagram.com/bronxburnersrc/,"The Armory, 216 Fort Washington Ave, New York,...",None,None,ERROR,name 'gmaps' is not defined,None
2,Bronx Femme Run,Bronx,https://www.instagram.com/bronxfemmerun/,"Joseph Yancey Track, East 161st St. &, Macombs...",None,None,ERROR,name 'gmaps' is not defined,None
3,Bronx Nomads,Bronx,https://www.instagram.com/bronxnomads/,"Williamsbridge Oval Park, 2335 Resevoir Oval E...",None,None,ERROR,name 'gmaps' is not defined,None
4,Bronx Nomads,Bronx,https://www.instagram.com/bronxnomads/,"Williamsbridge Oval Track, 2335 Resevoir Oval ...",None,None,ERROR,name 'gmaps' is not defined,None
...,...,...,...,...,...,...,...,...,...
293,Staten Island Athletic Club,Staten Island,https://www.instagram.com/staten_island_athlet...,Clove Lakes Park,None,None,ERROR,name 'gmaps' is not defined,None
294,Staten Island Athletic Club,Staten Island,https://www.instagram.com/staten_island_athlet...,Silver Lake Park,None,None,ERROR,name 'gmaps' is not defined,None
296,Staten Island Athletic Club,Staten Island,https://www.instagram.com/staten_island_athlet...,Greenbelt Nature Center,None,None,ERROR,name 'gmaps' is not defined,None
298,The Just Us Running Club,Staten Island,https://www.instagram.com/thejurcnyc/,Jus' Us Store,None,None,ERROR,name 'gmaps' is not defined,None
300,Yonkers Running Project aka YRP,Yonkers,https://www.instagram.com/yonkersrunningprojec...,100 main st Yonkers NY 10591,None,None,ERROR,name 'gmaps' is not defined,None

In [9]:
unique_clubs_error['api_status'] = 'OK'
unique_clubs.update(unique_clubs_error[['result_type', 'api_status' ,'latitude', 'longitude']])

In [10]:
final_clubs = unique_clubs.copy()
final_clubs = final_clubs.drop(298).drop(231)
final_clubs #final list of clubs

,Crew,Borough,Website,Location,latitude,longitude,api_status,formatted_address,result_type
0,Boogie Down Bronx Runners,Bronx,https://www.instagram.com/boogiedownbronxrunners/,Pelham Cornerstone Community Center - 785 Pelh...,None,None,OK,name 'gmaps' is not defined,None
1,Bronx Burners,Bronx,https://www.instagram.com/bronxburnersrc/,"The Armory, 216 Fort Washington Ave, New York,...",None,None,OK,name 'gmaps' is not defined,None
2,Bronx Femme Run,Bronx,https://www.instagram.com/bronxfemmerun/,"Joseph Yancey Track, East 161st St. &, Macombs...",None,None,OK,name 'gmaps' is not defined,None
3,Bronx Nomads,Bronx,https://www.instagram.com/bronxnomads/,"Williamsbridge Oval Park, 2335 Resevoir Oval E...",None,None,OK,name 'gmaps' is not defined,None
4,Bronx Nomads,Bronx,https://www.instagram.com/bronxnomads/,"Williamsbridge Oval Track, 2335 Resevoir Oval ...",None,None,OK,name 'gmaps' is not defined,None
...,...,...,...,...,...,...,...,...,...
292,Richmond Rockets,Staten Island,https://www.therichmondrockets.com/,Clove Lakes Park,None,None,OK,name 'gmaps' is not defined,None
293,Staten Island Athletic Club,Staten Island,https://www.instagram.com/staten_island_athlet...,Clove Lakes Park,None,None,OK,name 'gmaps' is not defined,None
294,Staten Island Athletic Club,Staten Island,https://www.instagram.com/staten_island_athlet...,Silver Lake Park,None,None,OK,name 'gmaps' is not defined,None
296,Staten Island Athletic Club,Staten Island,https://www.instagram.com/staten_island_athlet...,Greenbelt Nature Center,None,None,OK,name 'gmaps' is not defined,None
300,Yonkers Running Project aka YRP,Yonkers,https://www.instagram.com/yonkersrunningprojec...,100 main st Yonkers NY 10591,None,None,OK,name 'gmaps' is not defined,None

In [11]:
final_clubs[final_clubs['Crew'] == 'Rabbit Movers Running Club']
final_clubs

,Crew,Borough,Website,Location,latitude,longitude,api_status,formatted_address,result_type
0,Boogie Down Bronx Runners,Bronx,https://www.instagram.com/boogiedownbronxrunners/,Pelham Cornerstone Community Center - 785 Pelh...,None,None,OK,name 'gmaps' is not defined,None
1,Bronx Burners,Bronx,https://www.instagram.com/bronxburnersrc/,"The Armory, 216 Fort Washington Ave, New York,...",None,None,OK,name 'gmaps' is not defined,None
2,Bronx Femme Run,Bronx,https://www.instagram.com/bronxfemmerun/,"Joseph Yancey Track, East 161st St. &, Macombs...",None,None,OK,name 'gmaps' is not defined,None
3,Bronx Nomads,Bronx,https://www.instagram.com/bronxnomads/,"Williamsbridge Oval Park, 2335 Resevoir Oval E...",None,None,OK,name 'gmaps' is not defined,None
4,Bronx Nomads,Bronx,https://www.instagram.com/bronxnomads/,"Williamsbridge Oval Track, 2335 Resevoir Oval ...",None,None,OK,name 'gmaps' is not defined,None
...,...,...,...,...,...,...,...,...,...
292,Richmond Rockets,Staten Island,https://www.therichmondrockets.com/,Clove Lakes Park,None,None,OK,name 'gmaps' is not defined,None
293,Staten Island Athletic Club,Staten Island,https://www.instagram.com/staten_island_athlet...,Clove Lakes Park,None,None,OK,name 'gmaps' is not defined,None
294,Staten Island Athletic Club,Staten Island,https://www.instagram.com/staten_island_athlet...,Silver Lake Park,None,None,OK,name 'gmaps' is not defined,None
296,Staten Island Athletic Club,Staten Island,https://www.instagram.com/staten_island_athlet...,Greenbelt Nature Center,None,None,OK,name 'gmaps' is not defined,None
300,Yonkers Running Project aka YRP,Yonkers,https://www.instagram.com/yonkersrunningprojec...,100 main st Yonkers NY 10591,None,None,OK,name 'gmaps' is not defined,None

In [ ]:
df_preprocessed
grouped_df = df_preprocessed.groupby(['Borough', 'Crew', 'Location']).agg(
    Days=('Day', lambda x: list(x)),
    Times=('Time', lambda x: list(x)),
    Weekend=('Weekend', lambda x: list(x))
).reset_index()

def classify_day_type(day_list):
    if all(day_list):  # all True
        return 'Weekend'
    elif any(day_list):  # mix of True/False
        return 'Both'
    else:  # all False
        return 'Weekday'

# Preview the result
grouped_df['DayType'] = grouped_df['Weekend'].apply(classify_day_type)
grouped_df[grouped_df['Times'].apply(lambda x: len(x) >= 2 if isinstance(x, list) else False)]

,Borough,Crew,Location,Days,Times,Weekend,DayType
8,Bronx,Bronx Sole,"Franz Sigel Park, E. 153rd Street & Grand Conc...","[Tuesday, Saturday]","[6:15 PM, 10:00 AM]","[False, True]",Both
15,Bronx,Van Cortlandt Track Club,Van Cortland Park - West 242nd Street and Broa...,"[Tuesday, Saturday]","[7:00 PM, 8:00 AM]","[False, True]",Both
18,Brooklyn,BK Heights Run Club,Borough Hall,"[Monday, Tuesday, Wednesday, Thursday, Friday,...","[6:30 PM, 6:30 PM, 6:30 PM, 6:30 PM, 6:30 PM, ...","[False, False, False, False, False, True]",Both
20,Brooklyn,BK Heights Run Club,Under BK Bridge,"[Monday, Tuesday, Wednesday, Thursday, Friday]","[7:20 AM, 7:20 AM, 7:20 AM, 7:20 AM, 7:20 AM]","[False, False, False, False, False]",Weekday
22,Brooklyn,BK Run Project,Prospect Park - Grand Army Plaza entrance,"[Tuesday, Thursday]","[6:30 AM, 6:30 AM]","[False, False]",Weekday
26,Brooklyn,Black Men Run,Prospect Park - Grand Army Plaza entrance,"[Wednesday, Saturday, Weekend]","[7:15 PM, 8:00 AM, nan]","[False, True, False]",Both
28,Brooklyn,Brooklyn Rogues,Prospect Park (Grand Army Plaza),"[Tuesday, Thursday]","[6:00 AM, 6:00 AM]","[False, False]",Weekday
30,Brooklyn,Brooklyn Track Club,East River Track,"[Tuesday, Tuesday]","[7:00 AM, 7:00 PM]","[False, False]",Weekday
31,Brooklyn,Brooklyn Track Club,McCarren Park Track,"[Tuesday, Tuesday]","[7:00 AM, 7:00 PM]","[False, False]",Weekday
35,Brooklyn,Crown Heights Running Club,Prospect Park - Eastern Parkway & Franklin Ave,"[Friday, Saturday]","[6:30 AM, 8:00 AM]","[False, True]",Both
40,Brooklyn,Dashing Whippets,Prospect Park - Grand Army Plaza entrance,"[Thursday, Saturday]","[7:00 PM, 8:30 AM]","[False, True]",Both
47,Brooklyn,Front Runners New York,Brooklyn Bridge Park Pier 6,"[Tuesday, Thursday]","[7:00 PM, 7:00 PM]","[False, False]",Weekday
51,Brooklyn,Great Hill Track Club,Prospect Park - Flatbush Ave & Eastern Parkway,"[Tuesday, Thursday]","[6:30 PM, 6:30 PM]","[False, False]",Weekday
56,Brooklyn,NYC Sprint Collective,McCarren Park,"[Tuesday, Friday]","[6:00 PM, 8:00 AM]","[False, False]",Weekday
60,Brooklyn,North Brooklyn Runners,McCarren Park,"[Monday, Monday, Monday, Tuesday, Tuesday, Wed...","[6:45 AM, 7:30 PM, 9:10 PM, 6:30 AM, 7:30 PM, ...","[False, False, False, False, False, False, Fal...",Both
61,Brooklyn,North Brooklyn Runners,Prospect Park - Grand Army Plaza Entrance,"[Tuesday, Wednesday, Thursday]","[7:00 PM, 7:30 PM, 6:30 PM]","[False, False, False]",Weekday
66,Brooklyn,Positive Mental Energy,Bushwick - Maria Hernandez Park,"[Tuesday, Saturday]","[6:30 PM, 10:00 AM]","[False, True]",Both
68,Brooklyn,Prospect Park Track Club,Prospect Park - Entrance at Prospect Park West...,"[Wednesday, Sunday]","[7:00 PM, 9:00 AM]","[False, True]",Both
70,Brooklyn,Queers Run Brooklyn,Prospect Park Loop Starting at Brooklyn Centra...,"[1st & 3rd Monday, Tuesday, Thursday, Saturday...","[7:00 PM, 7:30 AM, 7:00 PM, 10:00 AM, 11:00 AM]","[False, False, False, True, False]",Both
74,Brooklyn,Ridge Runners NYC,"Bay Ridge - 4th Ave & 86th St, Brooklyn, NY 11209","[Saturday, Sunday]","[7:00 AM, 7:00 AM]","[True, True]",Weekend
79,Brooklyn,Running Souls Run Club,Prospect Park (Bartel-Pritchard Square entrance),"[Tuesday, Thursday, Saturday]","[7:00 PM, 7:00 PM, 9:45 AM]","[False, False, True]",Both
80,Brooklyn,South Brooklyn Running Club,Carroll Park (corner of Court and President),"[Monday, Tuesday, Wednesday, Friday, Sunday]","[6:45 AM, 7:15 PM, 7:00 PM, 6:45 AM, 4:00 PM]","[False, False, False, False, True]",Both
83,Brooklyn,Spartan Sundays Run Club,Prospect Lefferts Gardens - Wingate Track - 60...,"[Monday, Wednesday]","[6:00 AM, 6:00 AM]","[False, False]",Weekday
86,Brooklyn,Williamsburg Track Club,McCarren Park Track,"[Tuesday, Thursday]","[6:30 PM, 7:30 PM]","[False, False]",Weekday
88,Manhattan,Achilles International NYC,"Central Park - Engineer's Gate, 2 E 90th St, N...","[Tuesday, Saturday]","[6:00 PM, 10:15 AM]","[False, True]",Both
89,Manhattan,Adidas Runners,"Columbus Circle - NY Running Co, 10 Columbus C...","[Tuesday, Thursday]","[7:00 PM, 7:00 PM]","[False, False]",Weekday
96,Manhattan,Central Park Running Club,Central Park - Boat House,"[Tuesday, Thursday]","[6:30 AM, 6:30 AM]","[False, False]",Weekday
97,Manhattan,Central Park Track Club,Central Park,"[Tuesday, Thursday, Thursday]","[5:50 AM, 5:50 AM, 7:00 PM]","[False, False, False]",Weekday
99,Manhattan,Dashing Whippets,Central Park - 72nd by Bethesda Fountain,"[Monday, Monday, Tuesday, Thursday]","[7:00 AM, 7:00 PM, 7:00 PM, 7:00 PM]","[False, False, False, False]",Weekday
100,Manhattan,Dashing Whippets,East River Track,"[Thursday, Thursday]","[7:00 AM, 7:00 PM]","[False, False]",Weekday
111,Manhattan,Fleet Feet Running Club Columbus Circle,"NY Running Co, 10 Columbus Circle","[Wednesday, Sunday]","[6:30 PM, 8:30 AM]","[False, True]",Both
113,Manhattan,Front Runners New York,Central Park - across from Daniel Webster Statue,"[Wednesday, Saturday]","[7:00 PM, 10:00 AM]","[False, True]",Both
114,Manhattan,Great Hill Track Club,Central Park - 72nd Street Transverse and West...,"[Tuesday, Thursday]","[6:00 AM, 6:00 AM]","[False, False]",Weekday
115,Manhattan,Great Hill Track Club,"JackRabbit, 140 West 72nd Street","[Tuesday, Thursday]","[6:20 PM, 6:20 PM]","[False, False]",Weekday
119,Manhattan,Henwood Hounds Racing Team,Central Park,"[Friday, Sunday]","[nan, nan]","[False, True]",Both
127,Manhattan,New York Flyers,Central Park - West 72nd Street entrance,"[Tuesday, Thursday]","[6:00 AM, 6:00 AM]","[False, False]",Weekday
129,Manhattan,New York Harriers,"Central Park - Engineer's Gate, 2 E 90th St, N...","[Wednesday, Friday]","[6:30 AM, 6:30 AM]","[False, False]",Weekday
138,Manhattan,Not So Serious Running Group,Central Park - Central Park South and Center D...,"[Saturday, Sunday]","[10:00 AM, 10:00 AM]","[True, True]",Weekend
146,Manhattan,Pitch & Run,Chelsea Piers - Near Bluestone Lane Coffee,"[Monday, Friday]","[9:15 AM, 9:15 AM]","[False, False]",Weekday
155,Manhattan,Social Striders Running Club,Central Park South & 6th Avenue (Cit Bike Stat...,"[Thursday, Saturday, Sunday]","[7:00 AM, 10:00 AM, 10:00 AM]","[False, True, True]",Both
161,Manhattan,The Reservoir Dogs,Central Park - Hamilton Statue,"[Monday, Wednesday, Thursday, Saturday]","[7:00 PM, 7:00 PM, 7:00 PM, 9:30 AM]","[False, False, False, True]",Both
168,Manhattan,We Are NYC Running Club,"Central Park - Engineer's Gate, 2 E 90th St, N...","[Saturday, Saturday]","[7:00 AM, 8:00 AM]","[True, True]",Weekend
172,Manhattan,West Side YMCA Road Runners Club,"West Side YMCA, 5 W 63rd St., New York, NY 10023","[Monday, Wednesday]","[6:30 PM, 6:30 PM]","[False, False]",Weekday
174,Queens,Alley Pond Striders,Parkhouse on Winchester Boulevard,"[Saturday, Sunday]","[9:00 AM, 9:00 AM]","[True, True]",Weekend
179,Queens,Hellgate Road Runners,Astoria Park - Front of Field House,"[Thursday, Saturday, Saturday]","[7:30 PM, 8:40 AM, 9:00 AM]","[False, True, True]",Both
180,Queens,Hellgate Road Runners,Astoria Park - Inside track at NW corner near ...,"[Wednesday, Wednesday]","[6:00 AM, 7:30 PM]","[False, False]",Weekday
181,Queens,Hellgate Road Runners,Astoria Park - Shore Blvd on bottom lawn,"[Monday, Monday]","[6:15 AM, 7:30 PM]","[False, False]",Weekday
190,Queens,Queens Distance Runners,"Jackson Heights - The Queensboro, 80-02 Northe...","[Monday, Wednesday]","[6:00 PM, 6:30 PM]","[False, False]",Weekday
197,Queens,Run Hustle Run,"Richmond Hill - Hustle Barber Shop, 135-22 Hil...","[Tuesday, Sunday]","[7:00 PM, 6:45 AM]","[False, True]",Both
198,Queens,Run LIC,LIC - Corner 46th Rd & 5th St Meet,"[Monday, Thursday]","[7:00 AM, 6:30 PM]","[False, False]",Weekday
206,Queens,Woodside-Sunnyside Runners,Woodside Ave & 54th Street,"[Tuesday, Saturday]","[7:00 PM, 8:30 AM]","[False, True]",Both
209,Staten Island,Staten Island Athletic Club,Clove Lakes Park,"[Monday, Tuesday, Saturday]","[6:15 PM, 6:15 PM, 9:00 AM]","[False, False, True]",Both
212,Staten Island,The Just Us Running Club,Jus' Us Store,"[Monday, Tuesday]","[6:30 PM, 6:30 PM]","[False, False]",Weekday

In [258]:
unique_lists = grouped_df['Times'].dropna().apply(tuple).unique()
for item in unique_lists:
    print(list(item))

['Paused']
['8:00 AM']
['7:00 PM']
['6:30 PM']
['6:15 PM', '10:00 AM']
['6:00 PM']
['7:30 PM']
['7:00 PM', '8:00 AM']
['7:00 AM']
['6:30 PM', '6:30 PM', '6:30 PM', '6:30 PM', '6:30 PM', '8:00 AM']
['9:00 AM']
['7:20 AM', '7:20 AM', '7:20 AM', '7:20 AM', '7:20 AM']
['Varies - check website']
['6:30 AM', '6:30 AM']
['6:15 AM']
['6:30 AM']
['7:15 PM', '8:00 AM', nan]
['7:30 AM']
['6:00 AM', '6:00 AM']
[nan]
['7:00 AM', '7:00 PM']
['6:30 AM', '8:00 AM']
['7:00 PM', '8:30 AM']
['6:45 AM']
['7:15 AM']
['7:00 PM', '7:00 PM']
['6:30 PM', '6:30 PM']
['6:00 PM', '8:00 AM']
['8:30 AM']
['6:45 PM']
['6:45 AM', '7:30 PM', '9:10 PM', '6:30 AM', '7:30 PM', '6:00 AM', '7:00 PM', '6:30 AM', '7:30 PM', '8:00 AM', '9:00 AM', '8:00 AM']
['7:00 PM', '7:30 PM', '6:30 PM']
['6:28 AM']
['6:30 PM', '10:00 AM']
['7:00 PM', '9:00 AM']
['7:00 PM', '7:30 AM', '7:00 PM', '10:00 AM', '11:00 AM']
['6:50 PM']
['7:00 AM', '7:00 AM']
['8:00 PM']
['7:00 PM', '7:00 PM', '9:45 AM']
['6:45 AM', '7:15 PM', '7:00 PM', '6:45 AM', '4:00 PM']
['5:15 AM']
['6:30 PM', '7:30 PM']
['7:10 PM']
['6:00 PM', '10:15 AM']
['5:50 AM', '5:50 AM', '7:00 PM']
['7:00 AM', '7:00 PM', '7:00 PM', '7:00 PM']
['5:00 PM']
['6:15 PM']
['6:30 PM', '8:30 AM']
['7:00 PM', '10:00 AM']
['6:20 PM', '6:20 PM']
[nan, nan]
['5:30 PM']
['Varies']
['10:00 AM']
['10:00 AM', '10:00 AM']
['9:30 AM']
['9:15 AM', '9:15 AM']
['7:00 AM', '10:00 AM', '10:00 AM']
['7:00 PM', '7:00 PM', '7:00 PM', '9:30 AM']
['7:00 AM', '8:00 AM']
['7:15 PM']
['9:00 AM', '9:00 AM']
['8:05 AM']
['7:30 PM', '8:40 AM', '9:00 AM']
['6:00 AM', '7:30 PM']
['6:15 AM', '7:30 PM']
['6:00 AM']
['6:00 PM', '6:30 PM']
['7:00 PM', '6:45 AM']
['7:00 AM', '6:30 PM']
['6:15 PM', '6:15 PM', '9:00 AM']

## Create Interactive Google Map

https://www.iconicsandwiches.com/

**Task:** 

Generate an HTML template that displays an interactive Google Map with custom sandwich markers. When a marker is clicked, a Bootstrap modal should appear, showing sandwich details (restaurant name, sandwich name, price, description, image, location, website link, and a "Get Directions" link).

**Requirements:**

- Bootstrap for styling, including a fixed-top navbar and a fixed-bottom footer.
- Google Maps API for interactive map functionality.
- Custom Markers: Each marker should use a sandwich image as its icon.
- Bootstrap Modal: The modal should display:
   - Sandwich Name
   - Restaurant Name
   - Price
   - Description
   - Sandwich Image
   - Restaurant Location
   - Clickable Website Link
   - "Get Directions" link to Google Maps

**Data Structure:** 

The list of sandwich locations should be stored in an array of JavaScript objects. Each object should include:

{  
   'sandwich_name': 'Chorizo egg sandwich',  
   'restaurant': 'C&B',  
   'lat': 40.7250765,  
   'lng': -73.9816951,  
   'img': 'https://static01.nytimes.com/newsgraphics/2024-05-21-sandwich/_images/breakfast2-@@-300.webp',  
   'address': '178 East Seventh Street (Avenue B)',  
   'price': 13,  
   'description': 'Many people wouldn’t guess that C & B, .....',  
   'website': 'candbnyc.com'  
}

**Event Handling:** 

Clicking a marker should populate the modal with data from the corresponding object and display the modal.

**Additional Styling & Functionality:**

- The map should take up 100% width and full viewport height (100vh).
- The modal should be centered and mobile-friendly (modal-lg).
- Use Bootstrap utility classes for alignment and spacing.
- Include jQuery and Bootstrap scripts for modal functionality.

**Expected Output:** 

A full HTML, CSS, and JavaScript template that meets all the above specifications.

#### print python dictionaries for google map

In [ ]:
locations = []
for index, row in final_clubs.iterrows():
    location = {
        'RunClubName': row['Crew'],
        'Borough': row['Borough'],
        'Address': row['formatted_address'],
        'Website': row['Website']
    }
    locations.append(location)
locations

In [239]:
locations

[{'RunClubName': 'Boogie Down Bronx Runners',
  'Borough': 'Bronx',
  'Address': '785 Pelham Pkwy N, Bronx, NY 10467, USA',
  'Website': 'https://www.instagram.com/boogiedownbronxrunners/'},
 {'RunClubName': 'Bronx Burners',
  'Borough': 'Bronx',
  'Address': '216 Fort Washington Ave, New York, NY 10032, USA',
  'Website': 'https://www.instagram.com/bronxburnersrc/'},
 {'RunClubName': 'Bronx Femme Run',
  'Borough': 'Bronx',
  'Address': 'East 161st St. &, Macombs Dam Bridge, Bronx, NY 10451, USA',
  'Website': 'https://www.instagram.com/bronxfemmerun/'},
 {'RunClubName': 'Bronx Nomads',
  'Borough': 'Bronx',
  'Address': 'Holt Place and, Reservoir Oval E, Bronx, NY 10467, USA',
  'Website': 'https://www.instagram.com/bronxnomads/'},
 {'RunClubName': 'Bronx Nomads',
  'Borough': 'Bronx',
  'Address': '2335 Reservoir Oval E, Bronx, NY 10467, USA',
  'Website': 'https://www.instagram.com/bronxnomads/'},
 {'RunClubName': 'Bronx Rockets',
  'Borough': 'Bronx',
  'Address': 'Rev. T. Wendell Foster Park, 1055 Jerome Ave, Bronx, NY 10452, USA',
  'Website': 'https://www.instagram.com/bronx_rockets/'},
 {'RunClubName': 'Bronx Sole',
  'Borough': 'Bronx',
  'Address': 'Franz Sigel Park, Walton Ave & Gerard Ave., Grand Concourse bet. E. 151 St., E. 153 St. and, E 158th St, Bronx, NY 10451, USA',
  'Website': 'https://www.instagram.com/bronxsole/'},
 {'RunClubName': 'BX Endurance Runners',
  'Borough': 'Bronx',
  'Address': 'East 161st St. &, Macombs Dam Bridge, Bronx, NY 10451, USA',
  'Website': 'https://www.instagram.com/bxendurancerunners/'},
 {'RunClubName': 'BX Endurance Runners',
  'Borough': 'Bronx',
  'Address': 'Joyce Kilmer Park, 955 Walton Ave, Bronx, NY 10452, USA',
  'Website': 'https://www.instagram.com/bxendurancerunners/'},
 {'RunClubName': 'Great Hill Track Club',
  'Borough': 'Bronx',
  'Address': 'Van Cortlandt Park - 242 St, Bronx, NY 10471, USA',
  'Website': 'https://www.instagram.com/greathilltc/'},
 {'RunClubName': 'Mile Stylers',
  'Borough': 'Bronx',
  'Address': '940 Garrison Ave, Bronx, NY 10474, USA',
  'Website': 'https://www.instagram.com/milestylers/'},
 {'RunClubName': 'Startline Runners',
  'Borough': 'Bronx',
  'Address': 'Central Park, New York, NY, USA',
  'Website': 'https://www.eventbrite.com/o/startline-runners-31156520587'},
 {'RunClubName': 'Startline Runners',
  'Borough': 'Bronx',
  'Address': 'Tortoise & Hare Statue, 6087C Broadway, Bronx, NY 10471, USA',
  'Website': 'https://www.eventbrite.com/o/startline-runners-31156520587'},
 {'RunClubName': 'The Leftovers Run Club',
  'Borough': 'Bronx',
  'Address': 'East 161st St. &, Macombs Dam Bridge, Bronx, NY 10451, USA',
  'Website': 'https://www.instagram.com/theleftoversrun/'},
 {'RunClubName': 'Van Cortlandt Track Club',
  'Borough': 'Bronx',
  'Address': 'Van Cortlandt Park - 242 St, Bronx, NY 10471, USA',
  'Website': 'https://www.instagram.com/vancortlandttc/'},
 {'RunClubName': 'Van Cortlandt Track Club',
  'Borough': 'Bronx',
  'Address': 'Van Cortlandt Park, Broadway and Van, Cortlandt Park South, Bronx, NY 10471, USA',
  'Website': 'https://www.instagram.com/vancortlandttc/'},
 {'RunClubName': 'Achilles International NYC',
  'Borough': 'Brooklyn',
  'Address': 'Garfield Pl & Prospect Park W, Brooklyn, NY 11215, USA',
  'Website': 'https://www.instagram.com/achillesnyc/?hl=en'},
 {'RunClubName': 'Adidas Runners',
  'Borough': 'Brooklyn',
  'Address': 'Grand Army Plaza, Flatbush Ave, Brooklyn, NY 11238, USA',
  'Website': 'https://www.instagram.com/adidasrunners/'},
 {'RunClubName': 'Bed-Stuy Run Club',
  'Borough': 'Brooklyn',
  'Address': 'Halsey St & Saratoga Ave, Brooklyn, NY 11233, USA',
  'Website': 'https://www.instagram.com/__m.schmidt/'},
 {'RunClubName': 'Bedstuy Flyers',
  'Borough': 'Brooklyn',
  'Address': '1700 Fulton St, Brooklyn, NY 11213, USA',
  'Website': 'https://www.instagram.com/bedstuyflyers/'},
 {'RunClubName': 'Bedstuy Flyers',
  'Borough': 'Brooklyn',
  'Address': '570 Putnam Ave, Brooklyn, NY 11221, USA',
  'Website': 'https://www.instagram.com/bedstuyflyers/'},
 {'RunClubName': 'BK Heights Run Club',
  'Borough': 'Brooklyn',
  'Address': 'Dumbo, Brooklyn, NY 11201, USA',
  'Website': 'https://www.instagram.com/bkhrunclub/?hl=en'},
 {'RunClubName': 'BK Heights Run Club',
  'Borough': 'Brooklyn',
  'Address': '209 Joralemon St, Brooklyn, NY 11201, USA',
  'Website': 'https://www.instagram.com/bkhrunclub/?hl=en'},
 {'RunClubName': 'BK Heights Run Club',
  'Borough': 'Brooklyn',
  'Address': '401 Biscayne Blvd Unit M100, Miami, FL 33132, USA',
  'Website': 'https://www.instagram.com/bkhrunclub/?hl=en'},
 {'RunClubName': 'BK Run Project',
  'Borough': 'Brooklyn',
  'Address': 'Grand Army Plaza, Flatbush Ave, Brooklyn, NY 11238, USA',
  'Website': 'https://www.bkrunproject.com/'},
 {'RunClubName': 'BK Run Project',
  'Borough': 'Brooklyn',
  'Address': 'Prospect Park, Brooklyn, NY, USA',
  'Website': 'https://www.bkrunproject.com/'},
 {'RunClubName': 'Black Men Run',
  'Borough': 'Brooklyn',
  'Address': 'Grand Army Plaza, Flatbush Ave, Brooklyn, NY 11238, USA',
  'Website': 'https://www.instagram.com/blackmenrunnyc/'},
 {'RunClubName': 'Brooklyn Rogues',
  'Borough': 'Brooklyn',
  'Address': 'Grand Army Plaza, Flatbush Ave, Brooklyn, NY 11238, USA',
  'Website': 'https://www.instagram.com/brooklynrogues/'},
 {'RunClubName': 'Brooklyn Rogues',
  'Borough': 'Brooklyn',
  'Address': '30 Lafayette Ave, Brooklyn, NY 11217, USA',
  'Website': 'https://www.instagram.com/brooklynrogues/'},
 {'RunClubName': 'Brooklyn Track Club',
  'Borough': 'Brooklyn',
  'Address': '769 Lorimer St, Brooklyn, NY 11222, USA',
  'Website': 'https://www.brooklyntrackclub.com/training-sessions.html'},
 {'RunClubName': 'Brooklyn Track Club',
  'Borough': 'Brooklyn',
  'Address': 'East River Park, East River Promenade, New York, NY 10002, USA',
  'Website': 'https://www.brooklyntrackclub.com/training-sessions.html'},
 {'RunClubName': 'Brooklyn Track Club',
  'Borough': 'Brooklyn',
  'Address': 'Central Park, New York, NY, USA',
  'Website': 'https://www.brooklyntrackclub.com/training-sessions.html'},
 {'RunClubName': 'Brooklyn Track Club',
  'Borough': 'Brooklyn',
  'Address': 'Prospect Park, Brooklyn, NY, USA',
  'Website': 'https://www.brooklyntrackclub.com/training-sessions.html'},
 {'RunClubName': 'Brooklyn Tri Club',
  'Borough': 'Brooklyn',
  'Address': 'Center Dr, Brooklyn, NY, USA',
  'Website': 'https://brooklyntri.org/event/run-training-with-coach-john/2022-07-27'},
 {'RunClubName': 'Bushwick Runners',
  'Borough': 'Brooklyn',
  'Address': 'P33G+7F Maria Hernandez Park, Brooklyn, NY 11237, USA',
  'Website': 'https://www.instagram.com/bushwickrunners/'},
 {'RunClubName': 'Crown Heights Running Club',
  'Borough': 'Brooklyn',
  'Address': 'Prospect Park, Brooklyn, NY, USA',
  'Website': 'https://www.instagram.com/crownheightsrunningclub/'},
 {'RunClubName': 'Crown Heights Running Club',
  'Borough': 'Brooklyn',
  'Address': 'Prospect Park, Brooklyn, NY, USA',
  'Website': 'https://www.instagram.com/crownheightsrunningclub/'},
 {'RunClubName': 'Crown Heights Running Club',
  'Borough': 'Brooklyn',
  'Address': 'Grand Army Plaza, Flatbush Ave, Brooklyn, NY 11238, USA',
  'Website': 'https://www.instagram.com/crownheightsrunningclub/'},
 {'RunClubName': 'Crown Heights Running Club',
  'Borough': 'Brooklyn',
  'Address': 'Prospect Pk, Brooklyn, NY 11225, USA',
  'Website': 'https://www.instagram.com/crownheightsrunningclub/'},
 {'RunClubName': 'Dashing Whippets',
  'Borough': 'Brooklyn',
  'Address': '545 President St, Brooklyn, NY 11215, USA',
  'Website': 'https://www.instagram.com/dashingwhippets/'},
 {'RunClubName': 'Dashing Whippets',
  'Borough': 'Brooklyn',
  'Address': 'Grand Army Plaza, Flatbush Ave, Brooklyn, NY 11238, USA',
  'Website': 'https://www.instagram.com/dashingwhippets/'},
 {'RunClubName': 'DeFine New York Run Club',
  'Borough': 'Brooklyn',
  'Address': '266 Adelphi St, Brooklyn, NY 11205, USA',
  'Website': 'https://www.instagram.com/definenewyorkrunclub/?hl=en'},
 {'RunClubName': 'Democratic Socialists of America',
  'Borough': 'Brooklyn',
  'Address': '20 Grand Army Plz, Brooklyn, NY 11238, USA',
  'Website': 'https://socialists.nyc/running-club/'},
 {'RunClubName': 'Endorphins Running Club',
  'Borough': 'Brooklyn',
  'Address': 'Grand Army Plaza, Flatbush Ave, Brooklyn, NY 11238, USA',
  'Website': 'https://www.instagram.com/endorphinsrunning/?hl=en'},
 {'RunClubName': 'Fleet Feet Running Club Brooklyn',
  'Borough': 'Brooklyn',
  'Address': '151 7th Ave, Brooklyn, NY 11215, USA',
  'Website': 'https://www.instagram.com/fleetfeetbrooklyn/'},
 {'RunClubName': 'Fort Greene Runners',
  'Borough': 'Brooklyn',
  'Address': 'DeKalb, IL, USA',
  'Website': 'https://www.instagram.com/fortgreenerunners/'},
 {'RunClubName': 'Fort Greene Runners',
  'Borough': 'Brooklyn',
  'Address': 'Hanson Pl & Fulton St, Brooklyn, NY 11217, USA',
  'Website': 'https://www.instagram.com/fortgreenerunners/'},
 {'RunClubName': 'Front Runners New York',
  'Borough': 'Brooklyn',
  'Address': 'Prospect Park, Brooklyn, NY, USA',
  'Website': 'https://frny.org/activities'},
 {'RunClubName': 'Front Runners New York',
  'Borough': 'Brooklyn',
  'Address': 'Brooklyn Bridge Park Pier 6, Governors Island - Atlantic Avenue/Brooklyn Bridge Park Pier 6, Brooklyn, NY 11201, USA',
  'Website': 'https://frny.org/activities'},
 {'RunClubName': 'Girls Run NYC',
  'Borough': 'Brooklyn',
  'Address': '222 Grand St, Brooklyn, NY 11211, USA',
  'Website': 'https://www.instagram.com/girlsrunnyc/'},
 {'RunClubName': 'Goldfinger Track Club',
  'Borough': 'Brooklyn',
  'Address': '954 Putnam Ave, Brooklyn, NY 11221, USA',
  'Website': 'https://www.instagram.com/gftcbklyn/'},
 {'RunClubName': 'Great Hill Track Club',
  'Borough': 'Brooklyn',
  'Address': 'Prospect Park, Brooklyn, NY, USA',
  'Website': 'https://www.instagram.com/greathilltc/'},
 {'RunClubName': 'Greenpoint Runners',
  'Borough': 'Brooklyn',
  'Address': '37 Noble St, Brooklyn, NY 11222, USA',
  'Website': 'https://www.instagram.com/greenpointrunners/?hl=en'},
 {'RunClubName': 'Kings County Fitness Club',
  'Borough': 'Brooklyn',
  'Address': 'Fort Greene Park, Dekalb Avenue &, S Portland Ave, Brooklyn, NY 11205, USA',
  'Website': 'https://www.instagram.com/kingscountyfitnessclub/'},
 {'RunClubName': 'Lean Strong Fast',
  'Borough': 'Brooklyn',
  'Address': 'Grand Army Plaza, Flatbush Ave, Brooklyn, NY 11238, USA',
  'Website': 'https://www.instagram.com/lean.strong.fast/?hl=en'},
 {'RunClubName': 'MTHD by Oscar',
  'Borough': 'Brooklyn',
  'Address': '450 Warren St, Brooklyn, NY 11217, USA',
  'Website': 'https://www.instagram.com/mthdbyoscar/'},
 {'RunClubName': 'New York Flyers',
  'Borough': 'Brooklyn',
  'Address': 'Brooklyn, NY, USA',
  'Website': 'https://www.nyflyers.org/'},
 {'RunClubName': 'Nice Jewish Runners',
  'Borough': 'Brooklyn',
  'Address': 'Grand Army Plaza, Flatbush Ave, Brooklyn, NY 11238, USA',
  'Website': 'https://www.instagram.com/nicejewishrunners/'},
 {'RunClubName': 'No Bad Days Run Club',
  'Borough': 'Brooklyn',
  'Address': '34 River St, Savannah, GA 31401, USA',
  'Website': 'https://www.instagram.com/nbd_rc'},
 {'RunClubName': 'North Brooklyn Runners',
  'Borough': 'Brooklyn',
  'Address': 'McCarren Park, 776 Lorimer St, Brooklyn, NY 11222, USA',
  'Website': 'https://northbrooklynrunners.org/'},
 {'RunClubName': 'North Brooklyn Runners',
  'Borough': 'Brooklyn',
  'Address': 'Grand Army Plaza, Flatbush Ave, Brooklyn, NY 11238, USA',
  'Website': 'https://northbrooklynrunners.org/'},
 {'RunClubName': 'North Brooklyn Runners',
  'Borough': 'Brooklyn',
  'Address': '677 Kent Ave, Brooklyn, NY 11249, USA',
  'Website': 'https://northbrooklynrunners.org/'},
 {'RunClubName': 'November Project',
  'Borough': 'Brooklyn',
  'Address': 'Fort Greene Park, Dekalb Avenue &, S Portland Ave, Brooklyn, NY 11205, USA',
  'Website': 'https://november-project.com/brooklyn-ny/'},
 {'RunClubName': 'NYC Sprint Collective',
  'Borough': 'Brooklyn',
  'Address': 'McCarren Park, 776 Lorimer St, Brooklyn, NY 11222, USA',
  'Website': 'https://www.instagram.com/nycsprintcollective/'},
 {'RunClubName': 'Off the Hook Track Club',
  'Borough': 'Brooklyn',
  'Address': '155 Bay St, Brooklyn, NY 11231, USA',
  'Website': 'https://www.instagram.com/offthehooktc/'},
 {'RunClubName': 'On Williamsburg Run Club',
  'Borough': 'Brooklyn',
  'Address': 'Williamsburg, Brooklyn, NY, USA',
  'Website': 'https://www.eventbrite.com/e/on-williamsburg-tuesday-community-group-runs-tickets-796928252857?aff=oddtdtcreator'},
 {'RunClubName': 'Positive Mental Energy',
  'Borough': 'Brooklyn',
  'Address': 'P33G+7F Maria Hernandez Park, Brooklyn, NY 11237, USA',
  'Website': 'https://www.instagram.com/positivementalenergy.nyc/'},
 {'RunClubName': 'Prospect Park Track Club',
  'Borough': 'Brooklyn',
  'Address': 'Prospect Park, Brooklyn, NY, USA',
  'Website': 'https://www.instagram.com/prospectparktc/'},
 {'RunClubName': 'Prospect Park Track Club',
  'Borough': 'Brooklyn',
  'Address': 'Prospect Park, Brooklyn, NY, USA',
  'Website': 'https://www.instagram.com/prospectparktc/'},
 {'RunClubName': 'Prospect Park Track Club',
  'Borough': 'Brooklyn',
  'Address': 'Bartel-Pritchard Square, Prospect Park Southwest, Brooklyn, NY 11215, USA',
  'Website': 'https://www.instagram.com/prospectparktc/'},
 {'RunClubName': 'Queers Run Brooklyn',
  'Borough': 'Brooklyn',
  'Address': '10 Grand Army Plz, Brooklyn, NY 11238, USA',
  'Website': 'https://www.instagram.com/queersrunbrooklyn/'},
 {'RunClubName': 'Rabbit Movers Running Club',
  'Borough': 'Brooklyn',
  'Address': 'Columbus Cir, New York, NY, USA',
  'Website': 'https://www.instagram.com/rabbit.movers.running.club/?hl=en'},
 {'RunClubName': 'Rage and Release',
  'Borough': 'Brooklyn',
  'Address': '845 Dean St, Brooklyn, NY 11238, USA',
  'Website': 'https://www.instagram.com/rageandrelease/'},
 {'RunClubName': 'Resident Runners',
  'Borough': 'Brooklyn',
  'Address': '250 Ashland Pl, Brooklyn, NY 11217, USA',
  'Website': 'https://www.instagram.com/residentrunners/'},
 {'RunClubName': 'Ridge Runners NYC',
  'Borough': 'Brooklyn',
  'Address': '78th St & 3rd Ave, Brooklyn, NY 11209, USA',
  'Website': 'https://www.instagram.com/ridgerunnersnyc/ OR https://www.facebook.com/groups/ridgerunnersnyc'},
 {'RunClubName': 'Ridge Runners NYC',
  'Borough': 'Brooklyn',
  'Address': 'American Veterans Memorial Pier, Bay Ridge Ave, Brooklyn, NY 11209, USA',
  'Website': 'https://www.instagram.com/ridgerunnersnyc/ OR https://www.facebook.com/groups/ridgerunnersnyc'},
 {'RunClubName': 'Ridge Runners NYC',
  'Borough': 'Brooklyn',
  'Address': '8301 Shore Rd, Brooklyn, NY 11209, USA',
  'Website': 'https://www.instagram.com/ridgerunnersnyc/ OR https://www.facebook.com/groups/ridgerunnersnyc'},
 {'RunClubName': 'Ridge Runners NYC',
  'Borough': 'Brooklyn',
  'Address': 'Shore Rd & 79th St, Brooklyn, NY 11209, USA',
  'Website': 'https://www.instagram.com/ridgerunnersnyc/ OR https://www.facebook.com/groups/ridgerunnersnyc'},
 {'RunClubName': 'Ridge Runners NYC',
  'Borough': 'Brooklyn',
  'Address': '4th Ave & 86th St, Brooklyn, NY 11209, USA',
  'Website': 'https://www.instagram.com/ridgerunnersnyc/ OR https://www.facebook.com/groups/ridgerunnersnyc'},
 {'RunClubName': 'Running Souls Run Club',
  'Borough': 'Brooklyn',
  'Address': 'Bartel-Pritchard Square, Prospect Park Southwest, Brooklyn, NY 11215, USA',
  'Website': 'https://www.instagram.com/runningsoulsrun/'},
 {'RunClubName': 'South Brooklyn Running Club',
  'Borough': 'Brooklyn',
  'Address': 'Carroll Park, President St, Brooklyn, NY 11231, USA',
  'Website': 'https://www.instagram.com/southbrooklynrc/'},
 {'RunClubName': 'South Brooklyn Running Club',
  'Borough': 'Brooklyn',
  'Address': 'Red Hook Ball Fields 7, 98 Lorraine St, Brooklyn, NY 11231, USA',
  'Website': 'https://www.instagram.com/southbrooklynrc/'},
 {'RunClubName': 'Spartan Sundays Run Club',
  'Borough': 'Brooklyn',
  'Address': '600 Kingston Ave, Brooklyn, NY 11203, USA',
  'Website': 'https://www.instagram.com/spartansundaysrunclub/'},
 {'RunClubName': 'Spartan Sundays Run Club',
  'Borough': 'Brooklyn',
  'Address': '2133 Ralph Ave, Brooklyn, NY 11234, USA',
  'Website': 'https://www.instagram.com/spartansundaysrunclub/'},
 {'RunClubName': 'Team We Run Kings (Team WRK)',
  'Borough': 'Brooklyn',
  'Address': '150 Nevins St, Brooklyn, NY 11217, USA',
  'Website': 'https://werunkings.com/'},
 {'RunClubName': 'Ukrainian Running Club',
  'Borough': 'Brooklyn',
  'Address': '3030 Stillwell Ave, Brooklyn, NY 11224, USA',
  'Website': 'https://www.ukrainianrunningclub.com/'},
 {'RunClubName': 'Williamsburg Track Club',
  'Borough': 'Brooklyn',
  'Address': '769 Lorimer St, Brooklyn, NY 11222, USA',
  'Website': 'https://www.instagram.com/wbtc_nyc/'},
 {'RunClubName': 'Women Make Moves',
  'Borough': 'Brooklyn',
  'Address': '843 Sterling Pl, Brooklyn, NY 11216, USA',
  'Website': 'https://www.instagram.com/womenmakemoves/'},
 {'RunClubName': 'Achilles International NYC',
  'Borough': 'Manhattan',
  'Address': '2 E 90th St, New York, NY 10128, USA',
  'Website': 'https://www.instagram.com/achillesnyc/?hl=en'},
 {'RunClubName': 'Adidas Runners',
  'Borough': 'Manhattan',
  'Address': '10 Columbus Cir, New York, NY 10019, USA',
  'Website': 'https://www.instagram.com/adidasrunners/'},
 {'RunClubName': 'Almost Friday Run Club',
  'Borough': 'Manhattan',
  'Address': 'Morton St, New York, NY 10014, USA',
  'Website': 'https://www.instagram.com/almostfridayrunclub/?hl=en'},
 {'RunClubName': 'Beer Run Harlem Running Club (Rosie’s Run Club)',
  'Borough': 'Manhattan',
  'Address': '3604 Broadway 2nd FL, New York, NY 10031, USA',
  'Website': 'https://www.instagram.com/beerrunharlem/'},
 {'RunClubName': 'Blockhouse Run Club',
  'Borough': 'Manhattan',
  'Address': 'W 59th St, New York, NY 10019, USA',
  'Website': 'https://link.heylo.co/7co7 '},
 {'RunClubName': 'Bridge Runners',
  'Borough': 'Manhattan',
  'Address': '176 Delancey St, New York, NY 10002, USA',
  'Website': 'https://www.instagram.com/bridgerunners/?hl=en'},
 {'RunClubName': 'Bunji Running',
  'Borough': 'Manhattan',
  'Address': 'The Mall, New York, NY, USA',
  'Website': 'https://www.bunjirunning.com/'},
 {'RunClubName': 'Bunji Running',
  'Borough': 'Manhattan',
  'Address': 'Cat Hill ASCN 1ZZ, St Helena, Ascension and Tristan da Cunha',
  'Website': 'https://www.bunjirunning.com/'},
 {'RunClubName': 'Central Park Running Club',
  'Borough': 'Manhattan',
  'Address': 'Central Park Boat House, 72 E 72nd St, New York, NY 10021, USA',
  'Website': 'https://www.instagram.com/centralparkrunning/'},
 {'RunClubName': 'Central Park Track Club',
  'Borough': 'Manhattan',
  'Address': 'Central Park, New York, NY, USA',
  'Website': 'https://www.instagram.com/centralparktc/'},
 {'RunClubName': 'Dashing Whippets',
  'Borough': 'Manhattan',
  'Address': 'Central Park, New York, NY, USA',
  'Website': 'https://www.instagram.com/dashingwhippets/'},
 {'RunClubName': 'Dashing Whippets',
  'Borough': 'Manhattan',
  'Address': '80 W 3rd St, New York, NY 10012, USA',
  'Website': 'https://www.instagram.com/dashingwhippets/'},
 {'RunClubName': 'Dashing Whippets',
  'Borough': 'Manhattan',
  'Address': 'Central Park, New York, NY, USA',
  'Website': 'https://www.instagram.com/dashingwhippets/'},
 {'RunClubName': 'Dashing Whippets',
  'Borough': 'Manhattan',
  'Address': 'Riverbank State Park, 679 Riverside Dr, New York, NY 10031, USA',
  'Website': 'https://www.instagram.com/dashingwhippets/'},
 {'RunClubName': 'Dashing Whippets',
  'Borough': 'Manhattan',
  'Address': 'East River Park, East River Promenade, New York, NY 10002, USA',
  'Website': 'https://www.instagram.com/dashingwhippets/'},
 {'RunClubName': 'Dashing Whippets',
  'Borough': 'Manhattan',
  'Address': '10 Columbus Cir, New York, NY 10019, USA',
  'Website': 'https://www.instagram.com/dashingwhippets/'},
 {'RunClubName': 'Distance Project NYC',

In [ ]:
# locations

## Remove backgrounds from images

This was a pita pit of despair. ChatGPT led my to trying several python packages I could not install. I updated my python install. Still, nothing. That is until I discovered the image pig api on reddit.

https://imagepig.com/docs/#cutout

<br>

*Prompt 0 Chain-of-Thought*

I need to use the api below to remove the background from images. The image URLs are stored in a df column.

```python
from imagepig import ImagePig

imagepig = ImagePig("your-api-key")
result = imagepig.cutout("https://imagepig.com/static/street.jpeg")
result.save("cutout.png")
```

<br>

*Prompt 1 Chain-of-Thought*

Write the images to an 'output_dir'; check if it exists first, if not create it

<br>

*Prompt 2 Chain-of-Thought*

Name the image after the df['sandwich_name'] column
  
<br>
  
*Prompt 3 Chain-of-Thought*

There is a rate limit, i can only submit two images per minute

In [ ]:
import os
import shutil
import time
import re
from imagepig import ImagePig

# Define the directory for saving processed images
# output_dir = "processed_images_new_run"

# Check if the directory exists and delete all files inside
# if os.path.exists(output_dir):
#     for file in os.listdir(output_dir):
#         file_path = os.path.join(output_dir, file)
#         if os.path.isfile(file_path):
#             os.remove(file_path)
#         elif os.path.isdir(file_path):
#             shutil.rmtree(file_path)  # If there are subdirectories, delete them

# Create the directory if it doesn't exist
os.makedirs(output_dir, exist_ok=True)

# Get PIG API key
pig_api_key = os.getenv("PIG_API_KEY")

# Initialize ImagePig API
imagepig = ImagePig(pig_api_key)

# Function to sanitize filenames
def sanitize_filename(name):
    """Sanitize sandwich name to create a valid filename."""
    name = re.sub(r'[^\w\s-]', '', name)  # Remove special characters
    name = name.replace(" ", "_")  # Replace spaces with underscores
    return name.lower()  # Convert to lowercase for consistency

# Loop through each image URL in the 'image' column and process it
image_paths = []  # List to store paths of the processed images
for idx, (img_url, sandwich_name) in enumerate(zip(merged_df['image_final'], merged_df['sandwich'])):
    try:
        # Process the image using ImagePig
        result = imagepig.cutout(img_url)
        
        # Define the output filename using the sanitized sandwich name
        sanitized_name = sanitize_filename(sandwich_name)
        output_filename = f"{sanitized_name}.png"
        output_path = os.path.join(output_dir, output_filename)
        
        # Save the result to a file
        result.save(output_path)
        
        print(f"Processed and saved: {output_filename}")
        
        # Store the output path in the list
        image_paths.append(output_path)

        # If we've processed two images, sleep for a minute to respect the rate limit
        if (idx + 1) % 2 == 0:
            print("Rate limit reached. Sleeping for 60 seconds...")
            time.sleep(60)  # Sleep for 60 seconds (1 minute)
            
    except Exception as e:
        print(f"Failed to process image at {img_url}: {e}")
        image_paths.append(None)  # In case of failure, append None

# Add the image paths back to the DataFrame in the 'images_no_bg' column
merged_df['images_no_bg'] = image_paths

Processed and saved: chorizo_egg_sandwich.png
Processed and saved: smoked_salmon_sandwich.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: becl.png
Processed and saved: the_newhouse.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: shake_shack_breakfast_sandwich.png
Processed and saved: the_italian.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: the_casa.png
Processed and saved: egg_potato_and_cheese_hero.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: the_soho.png
Processed and saved: the_bomb.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: hlt.png
Processed and saved: crispy_chickn.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: scuttlebutt.png
Processed and saved: collard_greens_sandwich_on_focaccia.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: french_onion_sandwich.png
Processed and saved: vegan_bbq_pork_bao_bun.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: vegan_lobster_roll.png
Processed and saved: pastrami_on_rye.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: pastrami_egg_and_cheese.png
Processed and saved: wagyu_pastrami_sando.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: the_no_7.png
Processed and saved: classic_bagel_and_lox.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: chopped_cheese.png
Processed and saved: the_governors_choice.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: caviar_sandwich.png
Processed and saved: roll-n-roast_beef.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: do_it_for_johnny.png
Processed and saved: chopped_salad_sandwich.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: prosciutto__butter.png
Processed and saved: porchettaboutit.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: dill_party.png
Processed and saved: chicken_katsu_club.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: confit_tuna_melt.png
Processed and saved: tuna_salad.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: patty_melt.png
Processed and saved: the_pho_sandwich.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: shawarma_east_pita.png
Processed and saved: bánh_mì_xiú_mai.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: hot_ham_sandwich.png
Processed and saved: short_rib_barbacoa_cemita.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: cubano_sandwich.png
Processed and saved: focaccia_sandwich.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: chopped_chicharrón_and_brisket_sandwich.png
Processed and saved: bulgogi_fatboy.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: mille-feuille_pork_katsu_sando.png
Processed and saved: char_siu_bk_rib.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: the_lumberjack.png
Processed and saved: the_lumberjack.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: the_lumberjack.png
Processed and saved: the_lumberjack.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: the_lumberjack.png
Processed and saved: the_lumberjack.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: the_lumberjack.png
Processed and saved: the_lumberjack.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: the_lumberjack.png
Processed and saved: egg_katsu_sando.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: chicken_parm_hero.png
Processed and saved: chicken_parm_hero.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: uncle_rocco.png
Processed and saved: uncle_rocco.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: uncle_rocco.png
Processed and saved: uncle_rocco.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: michelangelo.png
Processed and saved: michelangelo.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: michelangelo.png
Processed and saved: michelangelo.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: michelangelo.png
Processed and saved: michelangelo.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: michelangelo.png
Processed and saved: veg-italian_sub.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: veg-italian_sub.png
Processed and saved: veg-italian_sub.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: chicken_caesar_wrap.png
Processed and saved: chicken_caesar_wrap.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: spicy_cumin_lamb_burger.png
Processed and saved: spicy_cumin_lamb_burger.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: spicy_cumin_lamb_burger.png
Processed and saved: spicy_cumin_lamb_burger.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: spicy_cumin_lamb_burger.png
Processed and saved: spicy_cumin_lamb_burger.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: spicy_cumin_lamb_burger.png
Processed and saved: spicy_cumin_lamb_burger.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: spicy_cumin_lamb_burger.png
Processed and saved: spicy_cumin_lamb_burger.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: spicy_cumin_lamb_burger.png
Processed and saved: spicy_cumin_lamb_burger.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: spicy_cumin_lamb_burger.png
Processed and saved: oxtail_macpatty.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: oxtail_macpatty.png
Processed and saved: oxtail_macpatty.png
Rate limit reached. Sleeping for 60 seconds...
Processed and saved: lil_rowdy_and_big_rowdy.png

In [ ]:
locations = []
for index, row in geo_cat_df.iterrows():
    location = {
        'sandwich_name': row['sandwich_name'],
        'restaurant': row['restaurant'],
        'lat': row['latitude'],
        'lng': row['longitude'],
        'img': row['image_url'],
        'address': row['address'],
        'price': row['price'],
        'description': row['description'],
        'website': row['website'],
        'img_no_bg': row['images_no_bg']
    }
    locations.append(location)